import { NextResponse } from "next/server";
import { listNewsItems } from "@/lib/news-store";
import { withResolvedImages } from "@/lib/source-images";

const TRANSLATIONS: Record<string, Record<string, string>> = {
  de: {
    "Source": "Quelle",
    "Relevant for your AI Workflow": "Relevant f\u00fcr deinen KI Workflow",
    "Relevant for the AI Workflow": "Relevant f\u00fcr den KI Workflow",
    "AI Workflow": "KI Workflow",
    "Model Context Protocol": "Modell-Kontext-Protokoll",
    "computer": "Computer",
    "model": "Modell",
    "Models": "Modelle",
    "language model": "Sprachmodell",
    "code": "Code",
    "agent": "KI-Agent",
    "agents": "KI-Agenten",
    "automation": "Automatisierung",
    "workflow": "Workflow",
    "tool": "Werkzeug",
    "dataset": "Datensatz",
    "training data": "Trainingsdaten",
    "data": "Daten",
    "privacy": "Datenschutz",
    "security": "Sicherheit",
    "cybersecurity": "Cybersicherheit",
    "tech": "Technologie",
    "artificial intelligence": "K\u00fcnstliche Intelligenz",
    "machine learning": "Maschinelles Lernen",
    "deep learning": "Tiefes Lernen",
    "neural network": "Neuronales Netz",
    "benchmark": "Benchmark",
    "evaluation": "Bewertung",
    "leaderboard": "Rangliste",
    "open source": "Open Source",
    "open-source": "Open Source",
    "release": "Freigabe",
    "launch": "Start",
    "announcement": "Ank\u00fcndigung",
    "update": "Aktualisierung",
    "news": "Neuigkeiten",
    "report": "Bericht",
    "study": "Studie",
    "research": "Forschung",
    "paper": "Paper",
    "analysis": "Analyse",
    "feature": "Funktion",
    "capability": "F\u00e4higkeit",
    "performance": "Leistung",
    "accuracy": "Genauigkeit",
    "generative": "generativ",
    "GPT": "GPT",
    "Claude": "Claude",
    "Gemini": "Gemini",
    "Llama": "Llama",
    "Mistral": "Mistral",
    "OpenAI": "OpenAI",
    "Anthropic": "Anthropic",
    "Meta": "Meta",
    "Microsoft": "Microsoft",
    "Google": "Google",
    "Amazon": "Amazon",
    "Reuters": "Reuters",
    "Ars Technica": "Ars Technica",
    "The Verge": "The Verge",
    "Wired": "Wired",
    "availability": "Verf\u00fcgbarkeit",
    "GitHub": "GitHub",
    "repository": "Repository",
    "API": "API",
    "endpoint": "Endpunkt",
    "server": "Server",
    "database": "Datenbank",
    "cloud": "Cloud",
    "infrastructure": "Infrastruktur",
    "deployment": "Bereitstellung",
    "production": "Produktion",
    "beta": "Beta",
    "preview": "Vorschau",
    "stable": "stabil",
    "version": "Version",
    "build": "Build",
    "test": "Test",
    "debug": "Debuggen",
    "error": "Fehler",
    "bug": "Bug",
    "fix": "Fix",
    "patch": "Patch",
    "vulnerability": "Sicherheitsl\u00fccke",
    "breach": "Verletzung",
    "leak": "Leck",
    "attack": "Angriff",
    "hack": "Hack",
    "malware": "Schadsoftware",
    "ransomware": "Ransomware",
    "phishing": "Phishing",
    "fake": "gef\u00e4lscht",
    "deepfake": "Deepfake",
    "scam": "Betrug",
    "fraud": "Betrug",
    "robotics": "Robotik",
    "robot": "Roboter",
    "drone": "Drohne",
    "autonomous": "autonom",
    "self-driving": "selbstfahrend",
    "vehicle": "Fahrzeug",
    "chip": "Chip",
    "processor": "Prozessor",
    "GPU": "GPU",
    "TPU": "TPU",
    "semiconductor": "Halbleiter",
    "patent": "Patent",
    "lawsuit": "Klage",
    "court": "Gericht",
    "judge": "Richter",
    "ruling": "Urteil",
    "regulation": "Regulierung",
    "law": "Gesetz",
    "bill": "Gesetzesentwurf",
    "policy": "Politik",
    "government": "Regierung",
    "ban": "Verbot",
    ".block": "Sperre",
    " ban": " Verbots",
    " ban ": " Verbot ",
    "license": "Lizenz",
    "price": "Preis",
    "cost": "Kosten",
    "revenue": "Umsatz",
    "profit": "Gewinn",
    "stock": "Aktie",
    "IPO": "B\u00f6rsengang",
    "funding": "Finanzierung",
    "investment": "Investition",
    "acquisition": "\u00dcbernahme",
    "merger": "Fusion",
    "partnership": "Partnerschaft",
    "deal": "Deal",
    "contract": "Vertrag",
    "enterprise": "Unternehmen",
    "business": "Gesch\u00e4ft",
    "/startup": "Startup",
    "company": "Unternehmen",
    "developer": "Entwickler",
    "engineer": "Ingenieur",
    "researcher": "Forscher",
    "scientist": "Wissenschaftler",
    "CEO": "Gesch\u00e4ftsf\u00fchrer",
    "founder": "Gr\u00fcnder",
    "team": "Team",
    "users": "Nutzer",
    "customers": "Kunden",
    "people": "Menschen",
    "society": "Gesellschaft",
    "world": "Welt",
    "industry": "Industrie",
    "sector": "Sektor",
    "market": "Markt",
    "competition": "Wettbewerb",
    "competitor": "Konkurrent",
    "rival": "Rivale",
    "vs": "gegen",
    "versus": "gegen",
  }
};

function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function translate(text: string, lang: string): string {
  if (lang === "en" || !text) return text || "";
  let result = text;
  const dict = TRANSLATIONS[lang] || {};
  for (const [key, value] of Object.entries(dict)) {
    const regex = new RegExp(escapeRegExp(key), "gi");
    result = result.replace(regex, value);
  }
  return result;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const limit = Math.max(1, Math.min(Number(searchParams.get("limit") ?? 50), 200));
  const lang = searchParams.get("lang") === "en" ? "en" : "de";
  
  const items = await listNewsItems(limit);
  const hydratedItems = await withResolvedImages(items);
  
  const translatedItems = hydratedItems.map(item => ({
    ...item,
    title: translate(item.title, lang),
    lead: translate(item.lead, lang),
    whyItMatters: translate(item.whyItMatters, lang),
  }));

  return NextResponse.json({
    generatedAt: new Date().toISOString(),
    total: translatedItems.length,
    items: translatedItems,
  });
}